### ISSUE TITLE
Scene Music

### ISSUE THREAD

**Issue by zeisss** [Velrok/dnd-mapper#14]
Something completly different: Maybe we can add background music when everything else works? :)

It would be cool if the DM can select something like tavern/dungeon/castle/field/forest etc and we have a preselected list of music for this somewhere.

**Comment by Velrok** [comment]
Thanks for the suggestion.

However I would consider this out of scope for this project.

Check out [Tabletop Audio](https://tabletopaudio.com/dungeon_sp.html) they allow you to create, save and broadcast a sound stage. Also it's free :)
